name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to the server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
            cd /path/to/your/project
            git pull origin main
            # You can add any additional deployment steps here (e.g., install dependencies)
            npm install
            npm run build
            pm2 restart app # (if you are using pm2 to manage the app)
          EOF
